#!/bin/sh
#
# A script to generate graphs based on include statements.
#
# This enables easy visualisation of the dependencies between files. However it
# can get easily overwhelming with large source trees.
#
# To use, just run at the base of the source tree, e.g.:
#     sh include-graph
#
# Which will then generate a file named "include-graph.pdf" which can then be
# viewed.

TYPE=pdf
FILE=include-graph.pdf

( echo "digraph include
{
	rankdir = LR"
	grep -Ir '#include' . |\
	sed -e '/BOOST/d' -e 's/^.\///' -e 's/[:"<>]//g' -e 's/#include//' |\
	awk '{ printf "\t\"%s\" -> \"%s\";\n", $1, $2 }'
echo "}" ) | dot -T$TYPE -o $FILE

echo "Wrote graph to \"$FILE\""
